name: fimber
description: Extensible logging for Flutter - based on Timber on Android, using similar (as far as Dart lang allows) method API with same concepts for tree and planting logging tree.
version: 0.6.1
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: '^1.16.5'
  pedantic: '^1.11.0'
