name: fimber
description: Extensible logging for Flutter - based on Timber on Android, using similar (as far as Dart lang allows) method API with same concepts for tree and planting logging tree.
version: 0.7.0
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lint: ^2.0.0
  test: ^1.0.0
