name: fimber_io
description: Version of Fimber package with support for File based loggers - dependent on dart::io
version: 0.6.6

homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  fimber: "^0.6.6"

dev_dependencies:
  lint: ^2.0.0
  test: ^1.0.0
